# Generated by Django 5.2.4 on 2026-01-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayMetadata',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('ended', 'Ended'), ('closed', 'Closed'), ('deleted', 'Deleted')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('file_path', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'day_metadata',
                'ordering': ['-date'],
            },
        ),
    ]
