# Generated by Django 5.2.4 on 2026-01-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('time_needed', models.IntegerField(help_text='Time needed in minutes')),
                ('is_bonus', models.BooleanField(default=False, help_text='Whether this service counts as a bonus turn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TechSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_alias', models.CharField(db_index=True, max_length=50)),
                ('service_name', models.CharField(db_index=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tech_skills',
                'ordering': ['tech_alias', 'service_name'],
                'unique_together': {('tech_alias', 'service_name')},
            },
        ),
    ]
