# Generated by Django 5.2.4 on 2026-01-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='short_name',
            field=models.CharField(blank=True, default='', help_text='Short display name for UI', max_length=50),
        ),
    ]
